INSERT INTO ingredient (name, category) VALUES
    ('Mozzarella', 'Dairy'),
    ('Garlic', 'Vegetable'),
    ('Chicken Breast', 'Meat'),
    ('Onion', 'Vegetable'),
    ('Carrot', 'Vegetable'),
    ('Potato', 'Vegetable'),
    ('Tortilla', 'Grain'),
    ('Banana', 'Fruit'),
    ('Almonds', 'Nuts'),
    ('Spinach', 'Vegetable'),
    ('Salmon', 'Fish'),
    ('Eggs', 'Dairy'),
    ('Rice', 'Grain'),
    ('Broccoli', 'Vegetable'),
    ('Yogurt', 'Dairy'),
    ('Beef', 'Meat'),
    ('Cucumber', 'Vegetable'),
    ('Bell Pepper', 'Vegetable'),
    ('Oats', 'Grain'),
    ('Strawberries', 'Fruit'),
    ('Walnuts', 'Nuts'),
    ('Zucchini', 'Vegetable'),
    ('Shrimp', 'Seafood'),
    ('Cabbage', 'Vegetable');

